=== mradbourne/message-format-wg/test/schemas/tests-schema-0.0.1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/unicode-org/message-format-wg/main/test/schemas/tests-schema-0.0.1.json",
  "title": "MessageFormat 2 data-driven tests source",
  "description": "This documents the format of MessageFormat 2 source test data.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "tests"
  ],
  "properties": {
    "scenario": {
      "type": "string",
      "description": "Identifier for the tests in the file"
    },
    "description": {
      "type": "string",
      "description": "Information about the test scenario."
    },
    "defaultTestProperties": {
      "$ref": "#/$defs/defaultTestProperties"
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/test"
      },
      "minItems": 1
    }
  },
  "$comment": "This allOf specifies required test properties that allow a default. A value will be required in 'defaultTestProperties' if one is not provided for every individual test.",
  "allOf": [
    {
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "required": [
                "testType"
              ]
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "required": [
                  "testType"
                ]
              }
            }
          }
        }
      ]
    },
    {
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "required": [
                "locale"
              ]
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "required": [
                  "locale"
                ]
              }
            }
          }
        }
      ]
    },
    {
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "required": [
                "src"
              ]
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "required": [
                  "src"
                ]
              }
            }
          }
        }
      ]
    },
    {
      "$comment": "Only one assertion is required. It doesn't matter which type.",
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "$ref": "#/$defs/anyExp"
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/anyExp"
              }
            }
          }
        }
      ]
    }
  ],
  "$defs": {
    "defaultTestProperties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "testType": {
          "$ref": "#/$defs/testType"
        },
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "src": {
          "$ref": "#/$defs/src"
        },
        "params": {
          "$ref": "#/$defs/params"
        },
        "exp": {
          "$ref": "#/$defs/exp"
        },
        "expCleanSrc": {
          "$ref": "#/$defs/expCleanSrc"
        },
        "expParts": {
          "$ref": "#/$defs/expParts"
        },
        "expErrors": {
          "$ref": "#/$defs/expErrors"
        }
      }
    },
    "test": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string",
          "description": "Information about the test."
        },
        "testType": {
          "$ref": "#/$defs/testType"
        },
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "src": {
          "$ref": "#/$defs/src"
        },
        "params": {
          "$ref": "#/$defs/params"
        },
        "exp": {
          "$ref": "#/$defs/exp"
        },
        "expCleanSrc": {
          "$ref": "#/$defs/expCleanSrc"
        },
        "expParts": {
          "$ref": "#/$defs/expParts"
        },
        "expErrors": {
          "$ref": "#/$defs/expErrors"
        },
        "only": {
          "type": "boolean",
          "description": "Normally not set. A flag to use during development to only run one or more specific tests."
        }
      }
    },
    "testType": {
      "description": "The category of test.",
      "enum": [
        "syntax",
        "function"
      ]
    },
    "locale": {
      "description": "The locale to use for formatting.",
      "type": "string"
    },
    "src": {
      "description": "The MF2 syntax source.",
      "type": "string"
    },
    "params": {
      "description": "Parameters to pass in to the formatter for resolving external variables.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/var"
      }
    },
    "var": {
      "type": "object",
      "oneOf": [
        {
          "additionalProperties": false,
          "required": [
            "value"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "value": {}
          }
        },
        {
          "required": [
            "type",
            "value"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "const": "datetime"
            },
            "value": {
              "type": "string"
            }
          }
        }
      ]
    },
    "exp": {
      "description": "The expected result of formatting the message to a string.",
      "type": "string"
    },
    "expCleanSrc": {
      "description": "The expected normalized form of `src`, for testing stringifiers.",
      "type": "string"
    },
    "expParts": {
      "description": "The expected result of formatting the message to parts.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "enum": [
              "markup",
              "literal",
              "fallback"
            ]
          },
          "kind": {},
          "name": {},
          "value": {},
          "source": {}
        },
        "oneOf": [
          {
            "additionalProperties": false,
            "required": [
              "kind",
              "name"
            ],
            "properties": {
              "type": {
                "const": "markup"
              },
              "kind": {
                "enum": [
                  "standalone",
                  "open",
                  "close"
                ]
              },
              "name": {
                "type": "string"
              },
              "options": {
                "$ref": "#/$defs/expPartOptions"
              }
            }
          },
          {
            "additionalProperties": false,
            "required": [
              "value",
              "valueType"
            ],
            "properties": {
              "type": {
                "const": "literal"
              },
              "value": {
                "type": "number"
              },
              "valueType": {
                "enum": [
                  "integer"
                ]
              },
              "options": {
                "$ref": "#/$defs/expPartOptions"
              }
            }
          },
          {
            "additionalProperties": false,
            "required": [
              "value"
            ],
            "properties": {
              "type": {
                "const": "literal"
              },
              "value": {
                "type": "string"
              },
              "options": {
                "$ref": "#/$defs/expPartOptions"
              }
            }
          },
          {
            "additionalProperties": false,
            "required": [
              "source"
            ],
            "properties": {
              "type": {
                "const": "fallback"
              },
              "source": {
                "type": "string"
              }
            }
          }
        ]
      }
    },
    "expPartOptions": {
      "description": "Expected option value within a part.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number"
        ]
      }
    },
    "expErrors": {
      "description": "The runtime errors expected to be emitted when formatting the message. If expErrors is either absent or empty, the message must be formatted without errors.",
      "type": [
        "array",
        "boolean"
      ],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "enum": [
              "bad-input",
              "bad-option",
              "missing-func",
              "not-selectable",
              "range-error",
              "unresolved-var",
              "unsupported-annotation",
              "unsupported-statement"
            ]
          }
        }
      }
    },
    "anyExp": {
      "anyOf": [
        {
          "required": [
            "exp"
          ]
        },
        {
          "required": [
            "expCleanSrc"
          ]
        },
        {
          "required": [
            "expParts"
          ]
        },
        {
          "required": [
            "expErrors"
          ]
        }
      ]
    }
  }
}

=== mradbourne/message-format-wg/test/tests/functions/date.json
{
  "scenario": "Date functions",
  "description": "The behaviour of built-in formatters is implementation-specific so the `exp` field is often omitted and assertions are made on error cases.",
  "defaultTestProperties": {
    "testType": "function",
    "locale": "en-US",
    "expErrors": false
  },
  "tests": [
    {
      "src": "{:date}",
      "exp": "{:date}",
      "expErrors": [
        {
          "type": "bad-input"
        }
      ]
    },
    {
      "src": "{horse :date}",
      "exp": "{|horse|}",
      "expErrors": [
        {
          "type": "bad-input"
        }
      ]
    },
    {
      "src": "{|2006-01-02| :date}"
    },
    {
      "src": "{|2006-01-02T15:04:06| :date}"
    },
    {
      "src": "{|2006-01-02| :date style=long}"
    },
    {
      "src": ".local $d = {|2006-01-02| :date style=long} {{{$d :date}}}"
    },
    {
      "src": ".local $t = {|2006-01-02T15:04:06| :time} {{{$t :date}}}"
    }
  ]
}
